name: CI-CD-Pipeline-Keerthana

on:
  pull_request:

jobs:
  build-test-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Run test cases
      run: |
        pytest app/test_app.py

    - name: Build Docker image
      run: docker build -t flask-ci-cd .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name flask-container flask-ci-cd

    - name: Show running container
      run: docker ps

    - name: Stop Docker container
      run: docker stop flask-container
